# Generated by Django 3.1.2 on 2020-11-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
