# Generated by Django 3.1.2 on 2020-10-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20201027_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='timeline_photo/%Y/%m/%d'),
        ),
    ]
