# Generated by Django 3.1.2 on 2020-11-02 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='updated',
        ),
    ]
