# Generated by Django 3.1.2 on 2020-11-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_remove_like_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created',
        ),
    ]
