# Generated by Django 3.1.2 on 2020-11-04 08:01

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('photo', '0002_auto_20201103_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.photo')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_taggedphoto_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='photo',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='photo.TaggedPhoto', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
