# Generated by Django 3.1.2 on 2020-11-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20201104_1706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaggedPhoto',
        ),
    ]
